-- Source : GRHUM (Oracle 19c)
-- Destination : PostgreSQL EXPORT_PERS
-- Rôle : Extraction des personnels actifs pour le projet SEBINA

CREATE OR REPLACE FORCE EDITIONABLE VIEW "GRHUM"."V_UHA_WSSIGB_PERS_EXPORT" (
    "LAST_NAME", "BIRTH_NAME", "FIRST_NAME", "GENDER", "BIRTH_PLACE", "BIRTH_DATE", 
    "STREET_FULL_WORK", "COMP_1_WORK", "COMP_2_WORK", "ZIP_CODE_WORK", "FOREIGN_LABEL_WORK", "CITY_WORK", "COUNTRY_CODE_WORK", "COUNTRY_WORK", 
    "PHONE_WORK", "MOBILE_WORK", 
    "STREET_FULL_HOME", "COMP_1_HOME", "COMP_2_HOME", "ZIP_CODE_HOME", "FOREIGN_LABEL_HOME", "CITY_HOME", "COUNTRY_CODE_HOME", "COUNTRY_HOME", 
    "PHONE_HOME", "MOBILE_HOME", 
    "TYPE_CARTE", "ID_OPAQUE", "PRIMARY_AFFILIATION", "ESTABLISHMENT", "MAIN_AFFECTATION", 
    "LIBRARY_REGISTRATION_FEE", "EDUCATION_LEVEL", "DELETION_DATE", "SUPANNEMPID", "UPDATE_DATE"
) AS 
SELECT DISTINCT
    VUE1.NOMUSUEL AS LAST_NAME,
    VUE1.PATRONYME AS BIRTH_NAME,
    VUE1.PRENOM AS FIRST_NAME,
    CASE VUE1.CIVILITE
        WHEN 'M.' THEN 'M'
        WHEN 'Mme' THEN 'F'
        WHEN 'Mlle' THEN 'F'
        ELSE ''
    END AS GENDER,
    IND.VILLE_DE_NAISSANCE AS BIRTH_PLACE,
    TO_CHAR (VUE1.DATENAISS, 'YYYY-MM-DD') AS BIRTH_DATE,
    -- Adresse Travail
    VUE1.ADR2 AS STREET_FULL_WORK,
    VUE1.ADR1 AS COMP_1_WORK,
    '' AS COMP_2_WORK,
    VUE1.ADRCP AS ZIP_CODE_WORK,
    '' AS FOREIGN_LABEL_WORK,
    VUE1.ADRVILLE AS CITY_WORK,
    ADR.C_PAYS AS COUNTRY_CODE_WORK,
    PAYS.LL_PAYS AS COUNTRY_WORK,
    '' AS PHONE_WORK, -- Alimenté par LDAP dans Talend
    '' AS MOBILE_WORK, -- Alimenté par LDAP dans Talend
    -- Adresse Domicile
    ADR.ADR_ADRESSE1 AS STREET_FULL_HOME,
    ADR.ADR_ADRESSE2 AS COMP_1_HOME,
    '' AS COMP_2_HOME,
    ADR.CODE_POSTAL AS ZIP_CODE_HOME,
    ADR.CP_ETRANGER AS FOREIGN_LABEL_HOME,
    ADR.VILLE AS CITY_HOME,
    ADR.C_PAYS AS COUNTRY_CODE_HOME,
    PAYS.LL_PAYS AS COUNTRY_HOME,
    -- Téléphones domicile (sous-requêtes)
    (SELECT PTEL3.NO_TELEPHONE FROM GRHUM.PERSONNE_TELEPHONE PTEL3 
     WHERE PTEL3.PERS_ID = VUE1.personneid AND PTEL3.TYPE_NO = 'TEL' AND PTEL3.TYPE_TEL = 'PRV' AND PTEL3.TEL_PRINCIPAL = 'O') AS PHONE_HOME,
    (SELECT PTEL4.NO_TELEPHONE FROM GRHUM.PERSONNE_TELEPHONE PTEL4 
     WHERE PTEL4.PERS_ID = VUE1.personneid AND PTEL4.TYPE_NO = 'MOB' AND PTEL4.TYPE_TEL = 'PRV' AND PTEL4.TEL_PRINCIPAL = 'O') AS MOBILE_HOME,
    'UHA' AS TYPE_CARTE,
    individuid AS ID_OPAQUE,
    CASE WHEN VUE1.TEM_ENSEIGNANT = 'O' THEN 'Faculty' ELSE 'Employee' END AS PRIMARY_AFFILIATION,
    'UHA' AS establishment,
    VUE1.LIBCOMP AS MAIN_AFFECTATION,
    'G' AS LIBRARY_REGISTRATION_FEE, -- G pour Gratuit (standard personnels)
    '' AS EDUCATION_LEVEL,
    -- Délai de grâce de 30 jours après fin de contrat
    DECODE (VUE1.fincontrat, NULL, 
        DECODE (VUE1.finelementcarriere, NULL, NULL, TO_CHAR (VUE1.finelementcarriere + 30, 'YYYY-MM-DD')),
        TO_CHAR (VUE1.fincontrat + 30, 'YYYY-MM-DD')) AS DELETION_DATE,
    individuid AS supannEmpId,
    TO_CHAR (SYSDATE, 'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS UPDATE_DATE
FROM PASSCAMPUS.V_UHA_WSSIGB_PERS VUE1
INNER JOIN GRHUM.INDIVIDU_ULR IND ON VUE1.personneid = IND.PERS_ID
-- Jointures adresses
LEFT JOIN GRHUM.REPART_PERSONNE_ADRESSE RPA ON RPA.PERS_ID = VUE1.personneid AND RPA.TADR_CODE = 'PERSO' AND RPA.RPA_VALIDE = 'O'
LEFT JOIN GRHUM.ADRESSE ADR ON ADR.ADR_ORDRE = RPA.ADR_ORDRE
LEFT JOIN GRHUM.PAYS PAYS ON PAYS.C_PAYS = ADR.C_PAYS
WHERE VUE1.NOMUSUEL <> 'TEST'
ORDER BY LAST_NAME ASC;
